# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master


timeoutInMinutes: 0

strategy:
  matrix:
    mac35:
      imageName: 'macos-10.13'
      python.version: '3.5'
    mac36:
      imageName: 'macos-10.13'
      python.version: '3.6'
    mac37:
      imageName: 'macos-10.13'
      python.version: '3.7'
    windows35:
      imageName: 'vs2017-win2016'
      python.version: '3.5'
    windows36:
      imageName: 'vs2017-win2016'
      python.version: '3.6'
    windows37:
      imageName: 'vs2017-win2016'
      python.version: '3.7'

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    python -m pip install numpy
    python -m pip install scipy
  displayName: 'Install dependencies'

- script: |
    python setup.py build --debug install
  displayName: 'build'

- script: |
    python tests/test_basic.py
  displayName: 'testing'
